### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by reefki** [BosNaufal/vue-loading-bar#3]
I'm using Browserify, when importing the component `import LoadingBar from 'vue-loading-bar';` returns

```
[21:29:26] gulp-notify: [Laravel Elixir] Browserify Failed!: Unexpected token

/Users/xxx/Sites/xxx/node_modules/vue-loading-bar/vue-loading-bar.vue:1
<style>
^
ParseError: Unexpected token
```

**Comment by BosNaufal** [comment]
Hey @reefki, Thank you for using vue-loading-bar :smile: 

Hmm, it's quite tough, I haven't met this problem before...
But For your issue, have you include 'vueify' Or something like that to process the vue file? :grin:

**Comment by reefki** [comment]
@BosNaufal Yes, I also have bunch of `.vue` files and all processed smoothly. It's quite strange for me, the console said the error was line 1. I tried to remove `<style>` block, still the same, tried remove `<template>` block got the same error.

**Comment by Vaerum** [comment]
+1 
I have the same problem

**Comment by BosNaufal** [comment]
Hey everybody, the problem seems similar to [this](https://github.com/greyby/vue-spinner/issues/2). So vue-loading-bar need to have a bundled js version which is contained the loading-bar component itself. :grin:

Lately, I have some issue about the elixir browserify. I'm feeling strange about it. Cause, as you can see, Vue-loading-bar was developed with browserify :confused: And it shouldn't have any trouble with browserify in elixir too.

**Comment by Vaerum** [comment]
Copy the .vue file into my resource folder worked for me (using laravel).
